### ISSUE TITLE
Limit Exception has changed not sure if this is correct

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/koryphe#270]
Limit Exception has changed not sure if this is correct
see:

https://github.com/gchq/Gaffer/pull/2645/files#diff-b74b26546aad3b9af7b48c211fee90cc95d66dd22329da881d177b1965c56333

**Comment by t92549** [comment]
Gaffer's `LimitedIterator` uses a custom `LimitExceededException` which is just a `RuntimeException` with a different name. This will be replaced with Koryphe's class, and we have decided that in Koryphe, a `RuntimeException` should be used rather than `NoSuchElementException`, because elements do exist beyond the limit but you have reached the limit. To be fixed in https://github.com/gchq/koryphe/issues/278
